version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resume_app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FLASK_APP=app.server
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resume_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 